possibility to sent survey for previous months
nokia-wroclaw/innovativeproject-health-care pull request #29
Opened 2020-03-10 12:12 UTC by martarzepa

2020-03-27 09:42 UTC, marcin992 requested changes

2020-03-27 09:42 UTC, marcin992 commented on backend/resources/surveys.py
> +#             abort(400, 'Only one answer per team is allowed.')
Please uncomment it

2020-03-27 09:42 UTC, marcin992 commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +const SurveyPage = ({ user, teams, currentTeamId, surveyIsActive, tribes, periods,  ...props }) => {
Set indentation to 2

2020-03-27 09:42 UTC, marcin992 commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +const SurveyPage = ({ user, teams, currentTeamId, surveyIsActive, tribes, periods,  ...props }) => {
`tribes` aren't used, you can remove it from props

2020-03-27 09:42 UTC, marcin992 commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +    }, [tribes]);
You can remove it

2020-03-27 09:42 UTC, marcin992 commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +    };
You can remove it

2020-03-27 09:42 UTC, marcin992 commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +    tribes: state.user.tribes || [],
You can remove it

2020-03-27 09:42 UTC, marcin992 commented on backend/resources/surveys.py
> +            print (period)
Remove print

2020-03-27 10:48 UTC, martarzepa commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +const SurveyPage = ({ user, teams, currentTeamId, surveyIsActive, tribes, periods,  ...props }) => {
done

2020-03-27 10:49 UTC, martarzepa commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +const SurveyPage = ({ user, teams, currentTeamId, surveyIsActive, tribes, periods,  ...props }) => {
done

2020-03-27 10:49 UTC, martarzepa commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +    }, [tribes]);
done

2020-03-27 10:50 UTC, martarzepa commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +    };
done

2020-03-27 10:51 UTC, martarzepa commented on frontend/src/components/SurveyPage/SurveyPage.jsx
> +    tribes: state.user.tribes || [],
done

2020-04-10 09:31 UTC, marcin992 approved these changes

2020-04-10 09:44 UTC, merged